# Generated by Django 2.2.4 on 2019-08-31 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_user_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Developer'), (1, 'Examiner')], null=True),
        ),
    ]
